/// Dialogue that gonna be shown to the player
//dialogue[0, 6] = "This is an extremely long sentence,\nused for debugging whether or not draw\ngui can line break itselves asdfasdfaasdfasdfadfafsfaf\n asdfasfdsafasdffasfdsafasdf"
//[0, 1] first value is assigned to someone's, a name, second value is the actual dialogue
dialogue[0, 0] = "Ko"
dialogue[0, 1] = "???: Wa! You scared me!!"
dialogue[0, 2] = "Ko: What are rare occurence.. It has been\nsuch a long time ever since i saw someone\nin this barren land."
dialogue[0, 3] = "My name is Ko! A scavenger! And your name\nis...?"
dialogue[0, 4] = "Mari: ...Mari."
dialogue[0, 5] = "Ko: ...Mkay! hello Mari! Where did you\ncome from? All i could see is white across\nthe horizon!"
dialogue[0, 6] = "Mari: I... don't know, i just seemingly\nwoke up in a dark cabin just nearby."
dialogue[0, 7] = "Ko: Well, i hope you're getting used with\nthis weather, your sweater does seems\ncomfy after all."
dialogue[0, 8] = "There is a warehouse nearby, you can\ndrop by for some food, but be sure to\nsave me some!"
dialogue[0, 9] = "And no need to keep your guard up\n, i pose no threat, there is no point\nfighting in this dying world."
dialogue[0, 10] = "Mari: Dying world...?"
dialogue[0, 11] = "Ko: Well, you did wake up in a dark cabin\nwith no memory after all.\nLet me fill you in."
dialogue[0, 12] = "Our world, named \"Icoris\", has been like\nthis for as long i remember."
dialogue[0, 13] = "It's dying, in quite a rapid way as you\ncan see, slowly being eaten by the\neternal freeze."
dialogue[0, 14] = "Blanketing the world with snow. It is\nabout to hit mankind's last bastion of\nhope."
dialogue[0, 15] = "The hope in the people is fading, i'm\njust a girl trying to get by, make the\nbest of my time."
dialogue[0, 16] = "Who knows? You suddenly appeared in such\na random way. What if you are our messiah?\nLike those fairytales?"
dialogue[0, 17] = "Mari: ..."
dialogue[0, 18] = "Ko: *giggle*, Ahem, well, there is a statue\nnearby, if you're gonna go sightseeing\nyou should check that out!"
dialogue[0, 19] = "Mari: ...Thank you."
dialogue[0, 20] = "Ko: You welcome! Off i go then!"
dialogue[0, 21] = "Ko: Aren't you gonna go sightseeing?"
//If canned food
dialogue[0, 22] = "Mari: Here, eat something."
dialogue[0, 23] = "Ko: !!\nYou actually saved me some food!"
dialogue[0, 24] = "So how did the sightseeing go?"
dialogue[0, 25] = "Mari: *giggle* I got to speak to the angel.\n"
dialogue[0, 26] = "Ko: I knew there is something suspicious\nabout it!"
dialogue[0, 27] = "A golden statue in the snow!\nI was right!"
dialogue[0, 28] = "Mari: I was expecting you to be shocked."
dialogue[0, 29] = "Ko: Haha, i was a little bit.\nSo? what did they tell you?"
dialogue[0, 30] = "Mari: Something something along\nthe line of i'm the messiah.\nNow i need to save the world!"
dialogue[0, 31] = "Oh yeah! Here, have a look at this!"
dialogue[0, 32] = "[You showed Ko the yellow dust.]"
dialogue[0, 33] = "Ko: It's warm!!\nThe snow patch around us turned\ninto grass again!"
dialogue[0, 34] = "Ko: But... if it's just you alone...\nHow are you gonna save Icoris in\ntime..?"
dialogue[0, 35] = "Mari: That's why i need your help!"
dialogue[0, 36] = "I need you to put some hope in me\nHelp me spread the news around!"
dialogue[0, 37] = "Ko: Mmm!"
dialogue[0, 38] = "I'll try my best!"
dialogue[0, 39] = "Oh! Here! Maybe this can help!"
dialogue[0, 40] = "Here is my id card!\nThe bridge from the east of\nthe warehouse require an id."
dialogue[0, 41] = "It leads to the last tropical island\non Icoris. Too bad it is filled\nwith scraps and litter."
dialogue[0, 42] = "Mari: That sounds both nice\nand sad at the same time.\nThe litter issue."
dialogue[0, 43] = "Ko: ...It is..but what can you do?\nEspecially in a dying world.."
dialogue[0, 44] = "Mari: Hey! i said spread the hope!\nNot despair!"
dialogue[0, 45] = "Ko: Haha, sorry sorry..."
dialogue[0, 46] = "I hope you safe travel then Mari?"
dialogue[0, 47] = "Mari: Yep! Off i go to the tropical\nisland!"
dialogue[0, 48] = "I'll see if there is anyone to\nask for help from!"
dialogue[0, 49] = "Hopefully i'll get to dip in\nthe water!"
dialogue[0, 50] = "Ko: I guess we depart here then..\nSafe travel Mari!"
dialogue[0, 51] = "Mari: You too...Ko!"
dialogue[0, 52] = "Mari: Let's go find that statue."

dialogue[1, 0] = "Introduction";
dialogue[1, 1] = "Press [SPACE] to interact.";
dialogue[1, 2] = "...";
dialogue[1, 3] = "...Mari...Mari...";
dialogue[1, 4] = "Mari: ..Who... is there...?";
dialogue[1, 5] = "...Mari...";
dialogue[1, 6] = "MARI!";
dialogue[1, 7] = "Mari: AHHHHHHHHHHHHHH";
dialogue[1, 8] = "WHERE AM I?!\nWHAT IS THIS PLACE?!";
dialogue[1, 9] = "WHAT ARE YOU PEOPLE GONna... do to me...?";
dialogue[1, 10] = "Narrator: You see yourself in this \nunfamilar room, realising it was just all a\ndream, you are trying to calm yourself\ndown.";
dialogue[1, 11] = "Mari: Sigh... nightmares.";
dialogue[1, 12] = "Speaking of waking up from a dream...\nWhere am i actually?";
dialogue[1, 13] = "BRRRR, cold...";
dialogue[1, 14] = "Hmm? There's a book there, is it glowing?\nOdd, i should check it out.";

dialogue[2, 0] = "Book in cabin";
dialogue[2, 1] = "Mari: ...The content of this book is weird.\nWhat is this book about?";
dialogue[2, 2] = "You stare at the glowing book.\nAs its glow you got more and more curious.\nLet open it!";
dialogue[2, 3] = "You read: Welcome to Messenger\nof the Frost!";
dialogue[2, 4] = "This book here covers about the\ninstruction of this game!";
dialogue[2, 5] = "In case you haven't know already,\n[W][A][S][D] is how you control your\ncharacter.";
dialogue[2, 6] = "[TAB] to open your inventory.\n[ESC] to exit the game!";
dialogue[2, 7] = "[M] to open progress menu.";
dialogue[2, 8] = "That's it! you've learned how to play MotF.\nIt is that simple!";
dialogue[2, 9] = "One more tip, remember, exploration is KEY.";
dialogue[2, 10] = "As you read this, a golden key suddenly\ndropped from the book.";
dialogue[2, 11] = "Golden Key added to inventory.";
dialogue[2, 12] = "Mari: I'm gonna bring it with me,\nin case it is needed for something.";
dialogue[2, 13] = "I'm gonna keep explore around,\ngonna see what going on.";

dialogue[3, 0] = "Outside"; 
dialogue[3, 1] = "What a view... this feels like i am on a\nfloating glacier.";
dialogue[3, 2] = "A white island surrounded by the\ndeep blue sea...Mmm...";
dialogue[3, 3] = "This place is blanketed with snow!\nGlad i got a sweater with me.";
dialogue[3, 4] = "I want to stick around for a bit...\nBut i need to investigate this area first.\nChecking if it's safe.";

dialogue[4, 0] = "Cabin lock"; 
dialogue[4, 1] = "Mari: Door's locked. Guess i need a key"; 
dialogue[4, 2] = "Mari: ...and... open!"; 

dialogue[5, 0] = "Talking to statue, not talking to Ko yet." // Label, untouched
dialogue[5, 1] = "Mari: My eyes hurt from staring at it..."
dialogue[5, 2] = "The light bounces of the snow\nand into the statue..."
dialogue[5, 3] = "Gotta find someone first.\nI'm gonna visit it again later."
//dialogue[5,0] = "After Ko"
dialogue[5, 4] = "Mari: Ko said i should visit this place."
dialogue[5, 5] = "What's so special about it?\nGold and all that."
dialogue[5, 6] = "Narrator: As you are carefully\ninspecting it. It began to glow."
dialogue[5, 7] = "Mari: ...WOA WHAT IS GOING ON?!\nA Glowing statue?!"
dialogue[5, 8] = "SO BRIGHT!!"
dialogue[5, 9] = "Angel: Oops! Sorry for scaring you!"
dialogue[5, 10] = "Mari: Ouch..."
dialogue[5, 11] = "Angel: Are you alright dear?"
dialogue[5, 12] = "Mari: ...kinda.."
dialogue[5, 13] = ".......wait.."
dialogue[5, 14] = "are you... TALKING?!"
dialogue[5, 15] = "Angel: ...yes.?"
dialogue[5, 16] = "Mari: What a weird world Icoris is..."
dialogue[5, 17] = "Angel: Ha, anyway, i saw you carrying\naround a golden book, mind if i ask where\ndid you get that from?"
dialogue[5, 18] = "Mari: I dunno, i woke up in this dark\ncabin, it was the light source of the entire\nplace."
dialogue[5, 19] = "Angel: !!!"
dialogue[5, 20] = "What is your name missy?"
dialogue[5, 21] = "Mari: Mari."
dialogue[5, 22] = "Angel: Well Mari..."
dialogue[5, 23] = "I'm sure you've talked to Ko?"
dialogue[5, 24] = "Mari: ...?"
dialogue[5, 25] = "Angel: Ko's a good girl.\nShe probably has told you about the\nworld ending already. Correct?"
dialogue[5, 26] = "Mari: ...She did."
dialogue[5, 27] = "Angel: That book, although was not\for you, it is very special."
dialogue[5, 28] = "Mari: Get to the point."
dialogue[5, 29] = "Angel: ..."
dialogue[5, 30] = "You, Mari, are our messiah."
dialogue[5, 31] = "Mari: I guess there's a reason i woke up\ninside a strange cabin. All too common."
dialogue[5, 32] = "Angel: The world has been like this for\ntoo long, people have lost their hope."
dialogue[5, 33] = "This dust right here is special.\nA little sprinkle of it can wipe out\na huge patch of snow."
dialogue[5, 34] = "I need you to help me gather\nmanpower. To help me spread the hope.\nShow them that it is possible\n"
dialogue[5, 35] = "Mari: Why didn't you ask for Ko's\nhelp?"
dialogue[5, 36] = "Angel: The one with the book is destined\nto save the world."
dialogue[5, 37] = "In other words, you're the chosen one."
dialogue[5, 38] = "Mari: ...*sigh*"
dialogue[5, 39] = "Got pulled into a random world,\nnow a messiah."
dialogue[5, 40] = "Well, what do i have to do?"
dialogue[5, 41] = "Angel: Take this bottle, it shows you how\nyou are doing in term of hopes."
dialogue[5, 42] = "The more hope you spread, the more\nhope it fills up."
dialogue[5, 43] = "Once it's full, the bottle\nwill explode, emitting the hope\ninto the world.\nThen turn into those yellow dust."
dialogue[5, 44] = "Try bringing Ko some food, see\n if it does fill up."
dialogue[5, 45] = "I entrust you with this mission.\nI beg you finish it."
dialogue[5, 46] = "Mari: That was a lot to take in\nbut alright. I'll try my best."
dialogue[5, 47] = "See you."
dialogue[5, 48] = "Angel: I Hope we will see again,\nmessiah."
dialogue[5, 49] = "[Strange bottle added to inventory.]\n[Press [M] to open.]"
dialogue[5, 50] = "[Yellow dust added to inventory.]"

dialogue[6, 0] = "Ticket bot on the bridge"
dialogue[6, 1] = "Bot: ID Card Please."
dialogue[6, 2] = "ID Card Request timed out."
dialogue[6, 3] = "Mari: I need to borrow an ID\ncard from someone."
dialogue[6, 4] = "ID Card valid. Gate opening."
dialogue[6, 5] = "ID Card valid. Gate opening." // Same dialogue because the previous one will be used for destroying the barrier

// Trent first encounter
dialogue[7, 0] = "Meeting Trent";
dialogue[7, 1] = "*Ruckus*";
dialogue[7, 2] = "Mari: Hello...";
dialogue[7, 3] = "*Ruckus*";
dialogue[7, 4] = "Mari: Heeellooo..?";
dialogue[7, 5] = "*Louder ruckus*";
dialogue[7, 6] = "Mari: HELLO!!!";
dialogue[7, 7] = "Trent: WOAH GET AWAY!!!";
dialogue[7, 8] = "I'M NOT THAT DELICous... Uhhh..";
dialogue[7, 9] = "Mari and Trent: ...";
dialogue[7, 10] = "Trent: Sorry for overreacting..";
dialogue[7, 11] = "Mari: It's alright, what's up!";
dialogue[7, 12] = "Trent: Name's Trent. Nice to meet you.";
dialogue[7, 13] = "Mari: Mari!";
dialogue[7, 14] = "Trent: Aren't you energetic, so what\nbrought you here?";
dialogue[7, 15] = "Mari: A friend of mine told me i\nshould pay a visit to this area.";
dialogue[7, 16] = "Her name is Ko, you know her?";
dialogue[7, 17] = "Trent: Ko...hmm..";
dialogue[7, 18] = "Oh Ko!! How's she doing?";
dialogue[7, 19] = "Mari: She doing well there, living by\nherself comfortably.";
dialogue[7, 20] = "She gave me her ID to visit here!";
dialogue[7, 21] = "Trent: That's nice.";
dialogue[7, 22] = "Mari: So what was that ruckus earlier?\n";
dialogue[7, 23] = "Trent: Oh! You see... one of my robot\nkinda just broke down..";
dialogue[7, 24] = "My luck of a thousand broken mirrors\naren't helping either! One of those rat\nbastard stole my wrench!";
dialogue[7, 25] = "So what you heard was me digging\nthrough the tool box, with a glimmer\nof hope that there will be another\nwrench.";
dialogue[7, 26] = "Mari: I can help.";
dialogue[7, 27] = "Trent: You sure? Those scavenger rat\ncan be dangerous!";
dialogue[7, 28] = "Mari: It's all good.";
dialogue[7, 29] = "Trent: Alright then... if you insist.\n";
dialogue[7, 30] = "It should be in that cave nearby.\n";
dialogue[7, 31] = "Stay safe!";
dialogue[7, 32] = "Mari: You too!\nI'll be back!";
// After wrench
dialogue[7, 33] = "Mari: I got your wrench!";
dialogue[7, 34] = "Wasn't that hard honestly.\nBig empty cave...";
dialogue[7, 35] = "...are you a scaredy cat?";
dialogue[7, 36] = "Trent: No... Ahem\nWell thanks for getting me my\nwrench!";
dialogue[7, 37] = "Do you want me to help with\nsomething?";
dialogue[7, 38] = "Mari: I do actually...";
dialogue[7, 39] = "So... as you already know..\nThe world is dying..";
dialogue[7, 40] = "Trent: I'm not robbing a store\nwith you.";
dialogue[7, 41] = "Mari: What? No!";
dialogue[7, 42] = "Do people ask you things like\nthis that often?";
dialogue[7, 43] = "Trent: ...sorry...";
dialogue[7, 44] = "Mari: Anyway...\nSee this yellow dust? Sprinkle this\ninto snow and they will magically\ndisappear!";
dialogue[7, 45] = "Trent: Wow, where did you get this?\nWe can finally live normally again!";
dialogue[7, 46] = "Mari: You won't believe it...\nAn angel gave me this...";
dialogue[7, 47] = "Trent: an angel...?";
dialogue[7, 48] = "Can't say i expected that but\nnothing too crazy.";
dialogue[7, 49] = "Mari: Not only Ko but you too?\nWhat kind of things did you guy\nsee?";
dialogue[7, 50] = "Trent: Best not say it, haha.";
dialogue[7, 51] = "Mari: hmph.";
dialogue[7, 52] = "Trent: What do you want me to do\nwith this?";
dialogue[7, 53] = "Mari: Could you create more\nrobots and spread this news to the local\nas well?";
dialogue[7, 54] = "Trent: Sure! Seeing this have given\nme hope again.";
dialogue[7, 55] = "I'll help you spread the news\naround. I'm sure the kid gonna love\nthis.";
dialogue[7, 56] = "Thank you for spreading us the hope.\n";
dialogue[7, 57] = "Mari: That is what my role is after\nall. A messiah.";
dialogue[7, 58] = "Trent: Well.. where are you gonna\ngo next?";
dialogue[7, 59] = "You should head for the city.\nMaybe the people there are gonna\nhelp you.";
dialogue[7, 60] = "Mari: That is my final destination then.\nHumanity's last bastion of hope.";
dialogue[7, 61] = "Trent: So... we part ways?";
dialogue[7, 62] = "Mari: Seems like it.\nIt has been short but it has been\nfun.";
dialogue[7, 63] = "Trent: Safe travel Mari.";
dialogue[7, 64] = "Mari: You too!\nGoodbye!";

dialogue[8, 0] = "Locked cave gate"
dialogue[8, 1] = "Mari: Maybe i should talk to that\nperson first."

dialogue[9,0] = "Try entering without talking to seira first"
dialogue[9,1] = "Mari: Maybe one day i'll be rich\nenough to get an apartment."

dialogue[10, 0] = "Talking to Seira for the first time";
dialogue[10, 1] = "Seira: Hello miss!";
dialogue[10, 2] = "Mari: I don't-";
dialogue[10, 3] = "Seira: PLEASE YOU HAVE TO HELP ME!!";
dialogue[10, 4] = "Mari: WOAH... What is it that you need me\nto help you with?\n(Thought she was an advertiser for a\nsecond.)";
dialogue[10, 5] = "Seira: I've been staring at this patch\nof grass for a while now...\nI am looking for an item...";
dialogue[10, 6] = "My tablet's pen... is missing..\nI definitely bought it with me\nwhen I go out!";
dialogue[10, 7] = "I was thinking of painting this\nscenery here, but the pen is not\nhere!";
dialogue[10, 8] = "Where could it have gone off to?\nI swear I bought it with me!";
dialogue[10, 9] = "If possible, could you check my\napartment please?";
dialogue[10, 10] = "I'm gonna keep looking around this area!";
dialogue[10, 11] = "Hopefully, I'm gonna find it!!";
dialogue[10, 12] = "Mari: ..........??????";
dialogue[10, 13] = "You want me, a total stranger\nto enter your private\ndormitory just like that?";
dialogue[10, 14] = "Wouldn't you be afraid of me stealing\nthings from you?";
dialogue[10, 15] = "I could go and look at your browsing\nhistory.";
dialogue[10, 16] = "And then share it everyone you know.";
dialogue[10, 17] = "Seira: On the other hand....\nMaybe I could go... instead..";
dialogue[10, 18] = "Miss stranger...? Where did you go...?";
// After getting the pen
dialogue[10, 19] = "Mari: Here you go!";
dialogue[10, 20] = "It was on your chair.\nIn broad daylight, clumsy girl.";
dialogue[10, 21] = "And you said \"i definitely brought it\nwith me!!\".";
dialogue[10, 22] = "Seira: Haha...did you go through my\nbrowser history?";
dialogue[10, 23] = "Mari: I did not.\nDon't know your password.";
dialogue[10, 24] = "Seira: So you would have done it\nif you had known my password..?";
dialogue[10, 25] = "Mari: No comment.";
dialogue[10, 26] = "Seira: *sigh*, well, what is your\nname...? Miss...?";
dialogue[10, 27] = "Mari: Mari.";
dialogue[10, 28] = "And you are...?";
dialogue[10, 29] = "Seira: Seira, i'm an artist.\nI was trying to make a new drawing.";
dialogue[10, 30] = "And you know... \"lost\" my pen.";
dialogue[10, 31] = "What about you miss Mari?";
dialogue[10, 32] = "Mari: No need for the formality.\nJust call me Mari.";
dialogue[10, 33] = "But yeah, my profession is kinda...\ncomplicated...";
dialogue[10, 34] = "Seira: That's okay!\nIf you don't want to talk about it,\nthen don't!";
dialogue[10, 35] = "I won't pry!";
dialogue[10, 36] = "Mari: Thank you.\nthat saves me a lot of explaining.";
dialogue[10, 37] = "Seira: Well? what are you gonna do now?\nWanna watch me paint instead?";
dialogue[10, 38] = "Mari: Sure!";
dialogue[10, 39] = "Seira: ...";
dialogue[10, 40] = "Mari: ...";
dialogue[10, 41] = "Seira: Let's start a convo.\nYou seem like you aren't from here\n";
dialogue[10, 42] = "Are you enjoying this city?\nIt's scenery?";
dialogue[10, 43] = "Mari: It is beautiful around here.";
dialogue[10, 44] = "Seira: Too bad the world is dying\nthough";
dialogue[10, 45] = "Mari: ...";
dialogue[10, 46] = "Seira: The snow it's approaching\nmeter by meter. It's getting colder.\n";
dialogue[10, 47] = "Ultimately we're all gonna perished.\nVery soon.";
dialogue[10, 48] = "Mari: ...speaking of the world\ndying..";
dialogue[10, 49] = "Wanna see something cool?";
dialogue[10, 50] = "Seira: What is it?";
dialogue[10, 51] = "Mari: You see those ice blocks\nfloating by the sea?";
dialogue[10, 52] = "Look at me as i scatter these\nyellow dust into the sea.";
dialogue[10, 53] = "[You take out the bag of dust\nand start to sprinkle it into\nthe sea]";
dialogue[10, 54] = "Seira: It is... MELTING??";
dialogue[10, 55] = "WOOOOOOOOOOOAHHHHHHHHHHHHHHH!!!!!!!";
dialogue[10, 56] = "Mari: Since you sorta asked me for help.\nI could ask you for your help right?";
dialogue[10, 57] = "Seira: Sure?";
dialogue[10, 58] = "Mari: Take some of these dust, and tell\neveryone about it, would you?";
dialogue[10, 59] = "Help me spread the words.";
dialogue[10, 60] = "Seira: Gladly!!!";
dialogue[10, 61] = "I'm so excited!!! I gotta go!\nSee you!";
dialogue[10, 62] = "Mari: Remember to share the news!";